// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty;

  global.subsetOfHash = function(hash, fnSelectKeyValue) {
    var h, k, v;
    h = {};
    for (k in hash) {
      v = hash[k];
      if (fnSelectKeyValue(k, v)) {
        h[k] = v;
      }
    }
    return h;
  };

  global.mapOfHash = function(hash, fnMapKeyValue) {
    var h, k, mappedKey, mappedValue, v, _ref;
    h = {};
    for (k in hash) {
      if (!__hasProp.call(hash, k)) continue;
      v = hash[k];
      _ref = fnMapKeyValue(k, v), mappedKey = _ref[0], mappedValue = _ref[1];
      h[mappedKey] = mappedValue;
    }
    return h;
  };

}).call(this);
