// Generated by CoffeeScript 1.4.0
(function() {

  global.objSubset = function(hash, fnSelectKeyValue) {
    var h, k, v;
    h = {};
    for (k in hash) {
      v = hash[k];
      if (fnSelectKeyValue(k, v)) {
        h[k] = v;
      }
    }
    return h;
  };

  global.objMap = function(hash, fnMapKeyValue) {
    var h, k, mappedKey, mappedValue, v, _ref;
    h = {};
    for (k in hash) {
      v = hash[k];
      _ref = fnMapKeyValue(k, v), mappedKey = _ref[0], mappedValue = _ref[1];
      console.log('mapping:', "" + k + ":" + v + " to " + mappedKey + ":" + mappedValue);
      h[mappedKey] = mappedValue;
    }
    return h;
  };

}).call(this);
