// Generated by CoffeeScript 1.4.0
(function() {

  global.node_env || (global.node_env = process.env.NODE_ENV || global.localEnvironment || 'development');

  module.exports = require('./hi-model-base');

}).call(this);
