// Generated by CoffeeScript 1.4.0
(function() {

  global.REDIS = require('redis-url');

  global.Mixin = require('hi-mixin');

  require('./environment');

  require('./extentions');

  require('./utils');

  require('./hash-utils');

  require('./redis-orm');

  require('./model-base');

}).call(this);
