// Generated by CoffeeScript 1.4.0
(function() {

  global.REDIS = require('redis-url');

  require('./environment');

  require('./extentions');

  require('./utils');

  require('./redis-orm');

  require('./model-base');

}).call(this);
