// Generated by CoffeeScript 1.4.0
(function() {
  var RedisORM,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RedisORM = (function(_super) {

    __extends(RedisORM, _super);

    function RedisORM() {
      return RedisORM.__super__.constructor.apply(this, arguments);
    }

    RedisORM.addTheseToClass = {
      find: function(info) {},
      XYZ: 'statix'
    };

    RedisORM.addTheseToInstance = {
      save: function() {},
      data: {
        a: 2
      }
    };

    return RedisORM;

  })(Mixin);

  global.RedisORM = RedisORM;

}).call(this);
