// Generated by CoffeeScript 1.4.0
(function() {
  var redisDBNum;

  redisDBNum = ORM_ENV.redis.dbNum;

  global.materializeRedisClient = function(callback) {
    var redis;
    redis = REDIS.connect(redisURL);
    if (redis == null) {
      if (callback != null) {
        callback(CAN_NOT_CONNECT);
      }
      throw CAN_NOT_CONNECT;
    }
    redis.select(redisDBNum, function(err, ok) {
      if (callback != null) {
        return callback(err, redis);
      }
    });
    return redis;
  };

}).call(this);
