// Generated by CoffeeScript 1.4.0
(function() {
  var mixinKeywords, redisDBNum,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  redisDBNum = ORM_ENV.redis.dbNum;

  global.materializeRedisClient = function(callback) {
    var redis;
    redis = REDIS.connect(redisURL);
    if (redis == null) {
      if (callback != null) {
        callback(CAN_NOT_CONNECT);
      }
      throw CAN_NOT_CONNECT;
    }
    redis.select(redisDBNum, function(err, ok) {
      if (callback != null) {
        return callback(err, redis);
      }
    });
    return redis;
  };

  mixinKeywords = ['extended', 'included'];

  global.extendMixin = function(klazz, mixin) {
    var key, value, _ref;
    for (key in mixin) {
      value = mixin[key];
      if (__indexOf.call(mixinKeywords, key) < 0) {
        klazz[key] = value;
      }
    }
    if ((_ref = mixin.extended) != null) {
      _ref.apply(klazz);
    }
    return klazz;
  };

  global.includeMixin = function(klazz, mixin) {
    var key, value, _ref;
    for (key in mixin) {
      value = mixin[key];
      if (__indexOf.call(mixinKeywords, key) < 0) {
        klazz.prototype[key] = value;
      }
    }
    if ((_ref = mixin.included) != null) {
      _ref.apply(klazz);
    }
    return klazz;
  };

}).call(this);
